# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-20 06:52
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('rango', '0002_auto_20160419_2245'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='slug',
            field=models.SlugField(default=datetime.datetime(2016, 4, 20, 6, 52, 56, 2701, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
